general {
    hide_cursor = true
    ignore_empty_input = true
}

background {
    monitor =
    path = screenshot
    blur_passes = 3
    blur_size = 8
    noise = 0.0117
    contrast = 0.8916
    brightness = 0.8172
    vibrancy = 0.1696
    vibrancy_darkness = 0.05
}

animations {
    enabled = true
    bezier = linear, 1, 1, 0, 0
    animation = fadeIn, 1, 3, linear
    animation = fadeOut, 1, 3, linear
    animation = inputFieldDots, 1, 2, linear
}

label {
    monitor =
    text = $TIME12
    color = rgba(e0def4ff)
    font_size = 72
    font_family = Inter
    position = 0, 140
    halign = center
    valign = center
}

label {
    monitor =
    text = cmd[update:60000] date +"%a, %B %e"
    color = rgba(e0def4dd)
    font_size = 24
    font_family = Inter
    position = 0, 80
    halign = center
    valign = center
}

input-field {
    monitor =
    size = 280, 56
    outline_thickness = 3
    dots_size = 0.25
    dots_spacing = 0.2
    dots_center = true
    fade_on_empty = false
    hide_input = false
    font_color = rgb(e0def4)
    inner_color = rgba(1f1d2ecc)
    outer_color = rgba(191724ff)
    check_color = rgba(eb6f92ff)
    fail_color = rgba(31748fff)
    placeholder_text = <span foreground="#e0def4aa">Password...</span>
    fail_text = <span foreground="#31748f">$FAIL</span>
    capslock_color = rgba(ebbcbaff)
    position = 0, 0
    halign = center
    valign = center
    rounding = 18
}

label {
    monitor =
    text = $ATTEMPTS failed attempts
    color = rgba(e0def4aa)
    font_size = 14
    font_family = Inter
    position = 0, -50
    halign = center
    valign = center
}
